[package]
name = "denote-rs-rename"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.4.7", features = ["derive"] }
chrono = "0.4.31"
anyhow = "1.0.75"
regex = "1.10.2"

[profile.release]
lto = true
opt-level = "s"
strip = "symbols"
codegen-units = 1
