[package]
name = "denote-rs"
version = "0.1.0"
edition = "2021"
authors = ["Artyom Kalin Vyacheslavovich <kalin.a.v20031@gmail.com>"]
repository = "https://github.com/5121f/denote-rs"
license = "MPL-2.0"
license-file = "LICENSE"

[dependencies]
clap = { version = "4.5.7", features = ["derive", "cargo"] }
chrono = "0.4.38"
anyhow = "1.0.86"
regex = "1.10.5"

[profile.release]
lto = true
opt-level = "s"
strip = "symbols"
codegen-units = 1
