[package]
name = "denote-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
chrono = "0.4.38"
anyhow = "1.0.86"
regex = "1.10.4"

[profile.release]
lto = true
opt-level = "s"
strip = "symbols"
codegen-units = 1
